const API_URL="https://i.eptonline.org/quiz.php";
let quiz=null,user=null,answers={},startedAt=0,timerId=null,strikes=0,submitted=false;
const app=document.getElementById("app"),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function getJSON(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw Error("Unable to load "+url);return r.json();}
async function login(e){e.preventDefault();try{const users=await getJSON("users.json"),email=document.getElementById("email").value.trim().toLowerCase(),pass=document.getElementById("password").value,found=users.find(u=>u.email.toLowerCase()===email&&u.password===pass);if(!found)throw Error("Invalid credentials.");user=found;localStorage.setItem("quizUser",JSON.stringify(found));showHome()}catch(x){document.getElementById("err").textContent=x.message}}
function showLogin(){app.innerHTML=`<section class="card"><div class="brand"><div class="badge">Q</div><div><h1>Secure Quiz Portal</h1><div class="muted">Authorized student access</div></div></div><form id="login"><label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" required><div id="err" class="error"></div><div class="actions"><button class="btn primary">Sign In</button></div></form></section>`;document.getElementById("login").onsubmit=login}
function showHome(){app.innerHTML=`<section class="card"><div class="brand"><div class="badge">Q</div><div><h1>${esc(quiz.title)}</h1><div class="muted">${esc(user.name||user.email)} · ${esc(user.institution)}</div></div></div><div class="notice"><b>Time:</b> ${quiz.timeLimitMinutes} minutes · <b>Attempts:</b> one</div><p>Read the instructions before starting. Focus changes are monitored.</p><div class="actions"><button id="start" class="btn gold">Start Quiz</button><button id="logout" class="btn danger">Log Out</button></div></section>`;start.onclick=showRules;logout.onclick=()=>{localStorage.removeItem("quizUser");location.reload()}}
function showRules(){const d=document.createElement("div");d.className="modal-backdrop";d.innerHTML=`<div class="modal"><h2>Quiz Instructions</h2><ul class="rules"><li>Complete the quiz within the time limit.</li><li>Do not copy, paste, inspect, or use prohibited shortcuts.</li><li>Leaving the tab/window causes a warning. Repeated focus loss submits the attempt.</li><li>Only one attempt is permitted per student.</li></ul><div class="actions"><button id="attempt" class="btn primary">Attempt Quiz</button><button id="cancel" class="btn">Cancel</button></div></div>`;document.body.appendChild(d);cancel.onclick=()=>d.remove();attempt.onclick=()=>{d.remove();startQuiz()}}
function startQuiz(){answers={};startedAt=Date.now();submitted=false;renderQuiz();guards();let sec=quiz.timeLimitMinutes*60;tick(sec);timerId=setInterval(()=>{--sec;tick(sec);if(sec<=0){clearInterval(timerId);submitQuiz("timeout")}},1000)}
function tick(s){const t=document.getElementById("timer");if(t)t.textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function renderQuiz(){app.innerHTML=`<div class="topbar"><b>${esc(quiz.title)}</b><span class="timer" id="timer"></span></div><main class="quiz-wrap"><form id="quizForm">${quiz.questions.map((q,i)=>qHTML(q,i)).join("")}<div class="actions"><button class="btn gold">Submit Quiz</button></div></form></main>`;quiz.questions.forEach(q=>{document.querySelectorAll(`[name="${q.id}"]`).forEach(x=>x.onchange=()=>answers[q.id]=q.type==="multi"?[...document.querySelectorAll(`[name="${q.id}"]:checked`)].map(y=>y.value):x.value);if(q.type==="text")document.getElementById(q.id).oninput=e=>answers[q.id]=e.target.value});quizForm.onsubmit=e=>{e.preventDefault();if(confirm("Submit your quiz now?"))submitQuiz("manual")}}
function qHTML(q,i){if(q.type==="text")return `<section class="qcard"><div class="qnum">Question ${i+1}</div><p><b>${esc(q.text)}</b></p><input id="${q.id}" type="text"></section>`;const typ=q.type==="multi"?"checkbox":"radio";return `<section class="qcard"><div class="qnum">Question ${i+1}</div><p><b>${esc(q.text)}</b></p>${q.options.map(o=>`<label class="option"><input type="${typ}" name="${q.id}" value="${esc(o)}">${esc(o)}</label>`).join("")}</section>`}
function guards(){document.addEventListener("contextmenu",stop);document.addEventListener("copy",stop);document.addEventListener("selectstart",stop);document.addEventListener("keydown",keys);document.addEventListener("visibilitychange",focus);window.addEventListener("blur",focus)}
function stop(e){if(!submitted)e.preventDefault()}function keys(e){if(e.key==="F12"||(e.ctrlKey&&["a","c","u","s","p"].includes(e.key.toLowerCase()))||(e.ctrlKey&&e.shiftKey&&["i","j","c"].includes(e.key.toLowerCase())))e.preventDefault()}function focus(){if(submitted||!document.hidden&&document.hasFocus())return;strikes++;alert(`Security warning: focus lost (${strikes}).`);if(strikes>=2)submitQuiz("focus_violation")}
async function submitQuiz(reason){if(submitted)return;submitted=true;clearInterval(timerId);const payload={user:{email:user.email,name:user.name,institution:user.institution,country:user.country,category:user.category},quizTitle:quiz.title,questions:quiz.questions.map(q=>({id:q.id,response:answers[q.id]??(q.type==="multi"?[]:"")})),timeTakenSeconds:Math.round((Date.now()-startedAt)/1000),clientReason:reason,submissionTimestamp:new Date().toISOString()};app.innerHTML=`<section class="card"><h2>Submitting…</h2><p class="muted">Please wait.</p></section>`;try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok||!d.success)throw Error(d.message||"Submission failed");app.innerHTML=`<section class="card"><h2>Submission Complete</h2><p>Your score: <b>${esc(d.score)}</b></p><p>Percentile: <b>${esc(d.percentile)}%</b></p><p>${esc(d.message)}</p></section>`}catch(e){submitted=false;app.innerHTML=`<section class="card"><h2>Submission Error</h2><p class="error">${esc(e.message)}</p><button class="btn primary" onclick="location.reload()">Return</button></section>`}}
(async()=>{try{quiz=await getJSON("quiz.json");const s=localStorage.getItem("quizUser");if(s)user=JSON.parse(s);user?showHome():showLogin()}catch(e){app.innerHTML=`<section class="card"><h2>Configuration Error</h2><p class="error">${esc(e.message)}</p></section>`}})();