const API="https://i.eptonline.org/quij/quiz.php";let user=null,quiz=null,attemptId=null,timer=null,startedAt=0,violations=0,submitting=false;
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const key=()=>"iarco_quiz_state_"+user.email.toLowerCase();const read=()=>{try{return JSON.parse(localStorage.getItem(key())||"null")}catch{return null}};const save=x=>localStorage.setItem(key(),JSON.stringify(x));
async function api(action,p={}){const r=await fetch(API+"?action="+action,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw Error(j.message||"Server error");return j}
function protect(){const b=e=>e.preventDefault();for(const n of ["contextmenu","copy","cut","dragstart","selectstart"])document.addEventListener(n,b);document.addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(e.key==="F12"||((e.ctrlKey||e.metaKey)&&["a","c","u","s","p"].includes(k))||(e.ctrlKey&&e.shiftKey&&["i","j","c"].includes(k)))e.preventDefault()})}
function login(){document.body.innerHTML=`<main class=shell><div class=card><h1 class=brand>IARCO Secure Quiz</h1><input id=email class=field type=email autocomplete=username placeholder=Email><input id=password class=field type=password autocomplete=current-password placeholder=Password><button id=login class="btn gold">Login</button><div id=msg></div></div></main>`;protect();document.querySelector("#login").onclick=async()=>{try{const list=await fetch("users.json",{cache:"no-store"}).then(r=>r.json()),email=document.querySelector("#email").value.trim().toLowerCase(),password=document.querySelector("#password").value,x=list.find(v=>v.email.toLowerCase()===email&&v.password===password);if(!x)throw Error("Invalid email or password");user={...x,email};localStorage.setItem("iarco_quiz_user",JSON.stringify(user));await api("login",user);home()}catch(e){document.querySelector("#msg").className="msg error";document.querySelector("#msg").textContent=e.message}}}
async function home(){let s=read();try{const r=await api("status",{email:user.email});if(r.exists){s={status:r.status,score:r.score,total_questions:r.total_questions,percentile:r.percentile,submitted_at:r.submitted_at};save(s)}}catch{}document.body.innerHTML=`<main class=shell><div class=card><h1 class=brand>Welcome, ${esc(user.name||user.email)}</h1><p>${esc(user.institution||"")}</p><div id=content></div></div></main>`;let c=document.querySelector("#content");if(s?.status==="COMPLETED")c.innerHTML=`<div class="msg success"><div class=score>${esc(s.score)}/${esc(s.total_questions)}</div><b>Already submitted.</b><br>Percentile: <b>${esc(s.percentile)}%</b><br>Submitted: ${esc(s.submitted_at||"")}</div><p class=small>Admin deletion is required for another attempt.</p>`;else if(s?.status==="CHEATED")c.innerHTML=`<div class="msg error"><b>Attempt closed.</b><br>${esc(user.name||user.email)}, a violation was recorded.</div>`;else if(s?.status==="STARTED")c.innerHTML=`<div class=msg>An attempt is already registered.</div>`;else{c.innerHTML=`<button id=start class="btn gold">Start Quiz</button>`;document.querySelector("#start").onclick=instructions}}
function instructions(){document.body.insertAdjacentHTML("beforeend",`<div class=overlay id=modal><div class=modal><h2>Quiz Instructions</h2><ul><li>One attempt unless admin deletes the record.</li><li>Do not switch tabs/windows.</li><li>Copy/right-click/developer shortcuts are blocked.</li><li>Violations are recorded.</li><li>Timer auto-submits.</li></ul><button id=attempt class="btn gold">Attempt Quiz</button></div></div>`);document.querySelector("#attempt").onclick=start}
async function start(){try{let q=await fetch("quiz.json",{cache:"no-store"}).then(r=>r.json()),v=q.variants[Math.floor(Math.random()*q.variants.length)];quiz={time_limit_minutes:q.time_limit_minutes||15,variant_id:v.id,questions:[...v.questions].sort(()=>Math.random()-.5).map(x=>({...x,options:x.options?[...x.options].sort(()=>Math.random()-.5):x.options}))};let r=await api("start",{email:user.email,name:user.name||"",institution:user.institution||"",country:user.country||"",category:user.category||"",variant_id:quiz.variant_id});attemptId=r.attempt_id;startedAt=Date.now();save({status:"STARTED",attempt_id:attemptId});document.querySelector("#modal")?.remove();render();guards();startTimer()}catch(e){alert(e.message)}}
function render(){document.body.innerHTML=`<div class=timer>Time left: <span id=time>--:--</span></div><main class=shell><div class=card><h1 class=brand>Quiz</h1><form id=form>${quiz.questions.map((q,i)=>`<section class=question><h3>${i+1}. ${esc(q.question)}</h3>${q.type==="single"?q.options.map(o=>`<label class=option><input type=radio name=q_${esc(q.id)} value="${esc(o)}"> ${esc(o)}</label>`).join(""):""}${q.type==="multi"?q.options.map(o=>`<label class=option><input type=checkbox name=q_${esc(q.id)} value="${esc(o)}"> ${esc(o)}</label>`).join(""):""}${q.type==="text"?`<input class=field name=q_${esc(q.id)} maxlength=500>`:""}</section>`).join("")}<button class="btn gold">Submit Quiz</button></form></div></main>`;document.querySelector("#form").onsubmit=e=>{e.preventDefault();submit("MANUAL")}}
function answers(){let o={};for(const q of quiz.questions){const a=[...document.querySelectorAll(`[name="q_${CSS.escape(q.id)}"]`)];o[q.id]=q.type==="multi"?a.filter(x=>x.checked).map(x=>x.value):(a.find(x=>x.checked)?.value??a[0]?.value??"")}return o}
function startTimer(){let s=(quiz.time_limit_minutes||15)*60;timer=setInterval(()=>{const e=document.querySelector("#time");if(e)e.textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;if(s<=0){clearInterval(timer);submit("TIMEOUT")}s--},1000)}
function guards(){const b=e=>e.preventDefault();document.addEventListener("contextmenu",b);document.addEventListener("copy",b);document.addEventListener("cut",b);document.addEventListener("visibilitychange",()=>{if(document.hidden&&!submitting)violate("VISIBILITY_CHANGE")});window.addEventListener("blur",()=>{if(!submitting)violate("WINDOW_BLUR")});document.addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(e.key==="F12"||((e.ctrlKey||e.metaKey)&&["a","c","u","s","p"].includes(k))||(e.ctrlKey&&e.shiftKey&&["i","j","c"].includes(k))){e.preventDefault();violate("BLOCKED_SHORTCUT")}})}
async function violate(reason){if(submitting)return;violations++;try{await api("violation",{attempt_id:attemptId,email:user.email,reason})}catch{}alert(`${user.name||user.email}, you tried to do cheating. This is recorded.`);if(violations>=2)submit("CHEATING")}
async function submit(reason){if(submitting)return;submitting=true;clearInterval(timer);try{let r=await api("submit",{attempt_id:attemptId,email:user.email,answers:answers(),time_taken:Math.round((Date.now()-startedAt)/1000),reason,variant_id:quiz.variant_id});let s={status:"COMPLETED",attempt_id:attemptId,score:r.score,total_questions:r.total_questions,percentile:r.percentile,submitted_at:r.submitted_at};save(s);document.body.innerHTML=`<main class=shell><div class=card><h1 class=brand>Submission Complete</h1><div class="msg success"><div class=score>${esc(r.score)}/${esc(r.total_questions)}</div>Percentile: <b>${esc(r.percentile)}%</b><br>Certificate email: <b>${esc(r.email_status)}</b></div></div></main>`}catch(e){submitting=false;alert(e.message);startTimer()}}
try{user=JSON.parse(localStorage.getItem("iarco_quiz_user")||"null")}catch{}user?home():login();
